# -*- coding: utf-8 -*-
"""App_starbucks

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xA-lseP0ywZqOWuSR3g02vRmz63Qg6oj
"""

import streamlit as st
import joblib
import numpy as np

# Title
st.title("Starbucks MLR Prediction Model")

# Load model (default path)
MODEL_PATH = "Starbucks_MLR.pkl"
model = joblib.load(MODEL_PATH)

# Input fields
amount_prepaid = st.number_input("Amount of Prepaid Card", min_value=0.0, step=0.1)
age = st.number_input("Age", min_value=0, step=1)
days_per_month = st.number_input("Days per month at Starbucks", min_value=0, step=1)
income = st.number_input("Income", min_value=0.0, step=100.0)

# Predict
if st.button("Predict"):
    features = np.array([[amount_prepaid, age, days_per_month, income]])
    prediction = model.predict(features)[0]
    st.write(f"### Predicted Cups of Coffee per day: {prediction:.2f}")